<?php

namespace MUSEE\LouvreBundle\Repository;

/**
 * OrdersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
 use Doctrine\ORM\EntityRepository;
 
class OrdersRepository extends \Doctrine\ORM\EntityRepository
{
}
